services:
  - type: web
    name: snake-rpg-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: 8498252537:AAFS94y2DJEUOVjOZHx0boHiVvbMrV1T7dc
      - key: WEBHOOK_URL
        value: https://testisk-zmeika.onrender.com
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    regions:
      - oregon
